# action.yml
name: 'Build AsciiDoctor Docker Action'
branding:
  icon: 'book-open'  
  color: 'white'
description: 'AsciiDoc Build action'
inputs:
    shellcommand:  # id of input
        description: 'AsciiDoc Build command'
        required: true
        default: 'asciidoctor index.adoc'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.shellcommand }}
    
    